export interface ErrorCustom {
  title: string;
  techTitle: string;
  code: any;
  isVisited: boolean;
}

export const errorCodes = {
  codes: [
    { code: 400, info: 'Bad Request' },
    { code: 401, info: 'Unauthorized' },
    { code: 402, info: 'Payment Required' },
    { code: 403, info: 'Forbidden' },
    { code: 404, info: 'Not Found' },
    { code: 405, info: 'Method Not Allowed' },
    { code: 406, info: 'Not Acceptable' },
    { code: 407, info: 'Proxy Authentication Required' },
    { code: 408, info: 'Proxy' },
    { code: 408, info: 'Request Timeout' },
    { code: 409, info: 'Conflict' },
    { code: 410, info: 'Gone' },
    { code: 411, info: 'Length Required' },
    { code: 412, info: 'Precondition Failed' },
    { code: 413, info: 'Payload Too Large' },
    { code: 414, info: 'URI Too Long' },
    { code: 415, info: 'Unsupported Media Type' },
    { code: 416, info: 'Range Not Satisfiable' },
    { code: 417, info: 'Expectation Failed' },
    { code: 418, info: 'I’m a teapot' },
    { code: 419, info: 'Authentication Timeout' },
    { code: 421, info: 'Misdirected Request' },
    { code: 422, info: 'Unprocessable Entity' },
    { code: 423, info: 'Locked' },
    { code: 424, info: 'Failed Dependency' },
    { code: 426, info: 'Upgrade Required' },
    { code: 428, info: 'Precondition Required' },
    { code: 429, info: 'Too Many Requests' },
    { code: 431, info: 'Request Header Fields Too Large' },
    { code: 449, info: 'Retry With' },
    { code: 451, info: 'Unavailable For Legal Reasons' },
    { code: 499, info: 'Client Closed Request' },
    { code: 500, info: 'Internal Server Error' },
    { code: 501, info: 'Not Implemented' },
    { code: 502, info: 'Bad Gateway' },
    { code: 503, info: 'Service Unavailable' },
    { code: 504, info: 'Gateway Timeout' },
    { code: 505, info: 'HTTP Version Not Supported' },
    { code: 506, info: 'Variant Also Negotiates' },
    { code: 507, info: 'Insufficient Storage' },
    { code: 508, info: 'Loop Detected' },
    { code: 509, info: 'Bandwidth Limit Exceeded' },
    { code: 510, info: 'Not Extended' },
    { code: 511, info: 'Network Authentication Required' },
    { code: 520, info: 'Unknown Error' },
    { code: 521, info: 'Web Server Is Down' },
    { code: 522, info: 'Connection Timed Out' },
    { code: 523, info: 'Origin Is Unreachable' },
    { code: 524, info: 'A Timeout Occurred' },
    { code: 525, info: 'SSL Handshake Failed' },
    { code: 526, info: 'Invalid SSL Certificate' },
  ],
};
