export const data = [
  {
    id: '5d0e36c9-3052-44a9-b879-0d6edb03b08b',
    id1C: '000000003',
    title: 'Автохимия и автокосметика',
    stringKey: 'avtoximiya-i-avtokosmetika000000003-61c86ee1',
    showCategory: false,
    child: [
      {
        id: 'ee9e7694-3af2-46e2-b672-ffe542f9d298',
        id1C: '000000028',
        parentId1C: '000000003',
        title: 'Средства для наружного применения',
        stringKey: 'sredstva-dlya-naruzhnogo-primeneniya000000028-3c624957',
        showCategory: false,
        child: [],
        icon: 'sredstva_naruj_prim_small.jpg',
        image: 'sredstva_naruj_prim_medium.jpg',
        seoTitle: '',
        seoDescription: '',
        seoKeywords: '',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Автохимия и автокосметика',
            url: 'avtoximiya-i-avtokosmetika000000003-61c86ee1',
          },
        ],
        isHasChild: false,
      },
      {
        id: 'd860efce-aa19-4dbf-9b97-944be623719d',
        id1C: '000000029',
        parentId1C: '000000003',
        title: 'Средства для применения внутри автомобиля',
        stringKey:
          'sredstva-dlya-primeneniya-vnutri-avtomobilya000000029-bba9288a',
        showCategory: false,
        child: [],
        icon: 'sredstva_vnutri_avto_small.jpg',
        image: 'sredstva_vnutri_avto_medium.jpg',
        seoTitle: '',
        seoDescription: '',
        seoKeywords: '',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Автохимия и автокосметика',
            url: 'avtoximiya-i-avtokosmetika000000003-61c86ee1',
          },
        ],
        isHasChild: false,
      },
      {
        id: '4a792f4e-b016-44f7-b907-7d4967f8a337',
        id1C: '000000067',
        parentId1C: '000000003',
        title: 'Средства для ухода за моторным отсеком',
        stringKey: 'sredstva-dlya-uxoda-za-motornym-otsekom000000067-df2670f0',
        showCategory: false,
        child: [],
        icon: 'motor_care_small.jpg',
        image: 'motor_care_medium.jpg',
        seoTitle: 'Средства для ухода за моторным отсеком',
        seoDescription: 'Средства для ухода за моторным отсеком',
        seoKeywords: 'Средства для ухода за моторным отсеком',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Автохимия и автокосметика',
            url: 'avtoximiya-i-avtokosmetika000000003-61c86ee1',
          },
        ],
        isHasChild: false,
      },
      {
        id: '86d0c3c7-5fe5-4411-b21a-3893a19a77a7',
        id1C: '000000068',
        parentId1C: '000000003',
        title: 'Сервисные продукты',
        stringKey: 'servisnye-produkty000000068-8be1217d',
        showCategory: false,
        child: [],
        icon: 'service_product_small.jpg',
        image: 'service_product_medium.jpg',
        seoTitle: 'Сервисные продукты',
        seoDescription: 'Сервисные продукты',
        seoKeywords: 'Сервисные продукты',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Автохимия и автокосметика',
            url: 'avtoximiya-i-avtokosmetika000000003-61c86ee1',
          },
        ],
        isHasChild: false,
      },
    ],
    icon: 'EF892527FDA07910B04F5AA3EEE6EF93',
    image: 'EF892527FDA07910B04F5AA3EEE6EF93',
    seoTitle: '',
    seoDescription: '',
    seoKeywords: '',
    isMain: true,
    isSale: false,
    isDropDownMenu: false,
    breadcrumbs: [{ title: 'Каталоги', url: '/catalog' }],
    isHasChild: true,
  },
  {
    id: '718a1b80-fe2a-467f-af11-2e5366d1d578',
    id1C: '000000086',
    title: 'Бытовая химия',
    stringKey: 'bytovaya-ximiya000000086-6e9b20c7',
    showCategory: false,
    child: [
      {
        id: '76ad0b6d-607a-4039-9283-26d48076ad1b',
        id1C: '000000087',
        parentId1C: '000000086',
        title: 'Средства для стирки',
        stringKey: 'sredstva-dlya-stirki000000087-26929466',
        showCategory: false,
        child: [],
        icon: 'stirka_small.jpg',
        image: 'stirka_medium.jpg',
        seoTitle: 'Средства для стирки',
        seoDescription: 'Средства для стирки',
        seoKeywords: 'Средства для стирки',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          { title: 'Бытовая химия', url: 'bytovaya-ximiya000000086-6e9b20c7' },
        ],
        isHasChild: false,
      },
      {
        id: 'cfc07006-879a-4ba9-ae26-b43add944109',
        id1C: '000000088',
        parentId1C: '000000086',
        title: 'Средства для пола',
        stringKey: 'sredstva-dlya-pola000000088-e4115411',
        showCategory: false,
        child: [],
        icon: 'pol_small.jpg',
        image: 'pol_medium.jpg',
        seoTitle: 'Средства для пола',
        seoDescription: 'Средства для пола',
        seoKeywords: 'Средства для пола',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          { title: 'Бытовая химия', url: 'bytovaya-ximiya000000086-6e9b20c7' },
        ],
        isHasChild: false,
      },
    ],
    icon: 'home_chemicals_small.jpg',
    image: 'home_chemicals_medium.jpg',
    seoTitle: 'Бытовая химия',
    seoDescription: 'Бытовая химия',
    seoKeywords: ' купить бытовую химию Тирасполь',
    isMain: true,
    isSale: false,
    isDropDownMenu: false,
    breadcrumbs: [{ title: 'Каталоги', url: '/catalog' }],
    isHasChild: true,
  },
  {
    id: '8fa1c605-d769-46c4-9730-30f96557f1f1',
    id1C: '000000011',
    title: 'Элементы крепления',
    stringKey: 'elementy-krepleniya000000011-beeaef37',
    showCategory: false,
    child: [
      {
        id: '4614ce33-9a38-4b9b-a0db-4482047cd70d',
        id1C: '000000077',
        parentId1C: '000000011',
        title: 'Болты',
        stringKey: 'bolty000000077-a9684d1',
        showCategory: false,
        child: [],
        seoTitle: 'Болты',
        seoDescription: 'Болты',
        seoKeywords: 'Болты',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: '0f739928-9e53-4373-9fd7-61f8b001beea',
        id1C: '000000078',
        parentId1C: '000000011',
        title: 'Гайки',
        stringKey: 'gajki000000078-343a4ebb',
        showCategory: false,
        child: [],
        seoTitle: 'Гайки',
        seoDescription: 'Гайки',
        seoKeywords: 'Гайки',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: '06ea6a97-184e-4935-952b-8b33693b1797',
        id1C: '000000079',
        parentId1C: '000000011',
        title: 'Крепление колеса',
        stringKey: 'kreplenie-kolesa000000079-6e655b76',
        showCategory: false,
        child: [],
        seoTitle: 'Крепление колеса',
        seoDescription: 'Крепление колеса',
        seoKeywords: 'Крепление колеса',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: 'de8107e7-50c6-4d5e-8679-8a41732b5b5d',
        id1C: '000000081',
        parentId1C: '000000011',
        title: 'Стяжки',
        stringKey: 'styazhki000000081-3410063f',
        showCategory: false,
        child: [],
        seoTitle: 'Стяжки',
        seoDescription: 'Стяжки',
        seoKeywords: 'Стяжки',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: 'a965e13f-e72b-482e-83c3-8c824b2e36ee',
        id1C: '000000082',
        parentId1C: '000000011',
        title: 'Хомуты',
        stringKey: 'xomuty000000082-7c15d584',
        showCategory: false,
        child: [],
        seoTitle: 'Хомуты',
        seoDescription: 'Хомуты',
        seoKeywords: 'Хомуты',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: '3c759ad0-1c8f-4301-85dd-9d8acd627080',
        id1C: '000000083',
        parentId1C: '000000011',
        title: 'Шплинты',
        stringKey: 'shplinty000000083-1741b6e1',
        showCategory: false,
        child: [],
        seoTitle: 'Шплинты',
        seoDescription: 'Шплинты',
        seoKeywords: 'Шплинты',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: '0c46a8ab-73a6-469c-ad93-01db297f9af8',
        id1C: '000000099',
        parentId1C: '000000011',
        title: 'Аксессуары для автотюнинга',
        stringKey: 'aksessuary-dlya-avtotyuninga000000099-314b4f96',
        showCategory: false,
        child: [],
        icon: 'autotuning_small.jpg',
        image: 'autotuning_medium.jpg',
        seoTitle: 'Аксессуары для автотюнинга',
        seoDescription: 'Аксессуары для автотюнинга',
        seoKeywords: 'Аксессуары для автотюнинга',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: 'd39c63d7-fdca-4f5a-83d6-5081fbda5278',
        id1C: '000000100',
        parentId1C: '000000011',
        title: 'Винты, Болты',
        stringKey: 'vinty-bolty000000100-12d6319',
        showCategory: false,
        child: [],
        icon: 'vint_small.jpg',
        image: 'vint_medium.jpg',
        seoTitle: 'Винты, Болты',
        seoDescription: 'Винты, Болты',
        seoKeywords: 'Винты, Болты',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: '09b88dd4-1b52-476d-a9d0-d3a953529075',
        id1C: '000000101',
        parentId1C: '000000011',
        title: 'Втулки, Вставки',
        stringKey: 'vtulki-vstavki000000101-70966aa7',
        showCategory: false,
        child: [],
        icon: 'vtulki_small.jpg',
        image: 'vtulki_medium.jpg',
        seoTitle: 'Втулки, Вставки',
        seoDescription: 'Втулки, Вставки',
        seoKeywords: 'Втулки, Вставки',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: 'ee9f569a-a404-4d41-a095-fe222566601a',
        id1C: '000000102',
        parentId1C: '000000011',
        title: 'Гайки, Шайбы',
        stringKey: 'gajki-shajby000000102-5a879d14',
        showCategory: false,
        child: [],
        icon: 'gaiki_small.jpg',
        image: 'gaiki_medium.jpg',
        seoTitle: 'Гайки, Шайбы',
        seoDescription: 'Гайки, Шайбы',
        seoKeywords: 'Гайки, Шайбы',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: 'ea56cb7b-8e2c-497f-a13c-2ecf04460c35',
        id1C: '000000107',
        parentId1C: '000000011',
        title: 'Детали механизма двери, замков',
        stringKey: 'detali-mexanizma-dveri-zamkov000000107-3535d08d',
        showCategory: false,
        child: [],
        icon: 'zamok_small.jpg',
        image: 'zamok_medium.jpg',
        seoTitle: 'Детали механизма двери, замков',
        seoDescription: 'Детали механизма двери, замков',
        seoKeywords: 'Детали механизма двери, замков',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: '96bb74ca-52dc-466f-87a2-b8d0599677ad',
        id1C: '000000103',
        parentId1C: '000000011',
        title: 'Детали освещения',
        stringKey: 'detali-osveshheniya000000103-c999b1d0',
        showCategory: false,
        child: [],
        icon: 'svet_small.jpg',
        image: 'svet_medium.jpg',
        seoTitle: 'Детали освещения',
        seoDescription: 'Детали освещения',
        seoKeywords: 'Детали освещения',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: 'e8db82eb-09c7-4208-9287-a7274090b6ab',
        id1C: '000000104',
        parentId1C: '000000011',
        title: 'Заглушки',
        stringKey: 'zaglushki000000104-e86a6795',
        showCategory: false,
        child: [],
        icon: 'zaglushki_small.jpg',
        image: 'zaglushki_medium.jpg',
        seoTitle: 'Заглушки',
        seoDescription: 'Заглушки',
        seoKeywords: 'Заглушки',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: 'a722a7c3-e49e-4657-9f5c-3f451973e4b9',
        id1C: '000000105',
        parentId1C: '000000011',
        title: 'Заклепки',
        stringKey: 'zaklepki000000105-9c56662a',
        showCategory: false,
        child: [],
        icon: 'zaklepki_small.jpg',
        image: 'zaklepki_medium.jpg',
        seoTitle: 'Заклепки',
        seoDescription: 'Заклепки',
        seoKeywords: 'Заклепки',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: 'a2fc6c43-94e5-4058-9432-26362b545ceb',
        id1C: '000000106',
        parentId1C: '000000011',
        title: 'Инструменты',
        stringKey: 'instrumenty000000106-46de8d28',
        showCategory: false,
        child: [],
        seoTitle: 'Инструменты',
        seoDescription: 'Инструменты',
        seoKeywords: 'Инструменты',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: '82e2ffcb-abd6-4195-85aa-7f3b0881b4c2',
        id1C: '000000108',
        parentId1C: '000000011',
        title: 'Крепления бампера/деталей бампера',
        stringKey: 'krepleniya-bamperadetalej-bampera000000108-e873d739',
        showCategory: false,
        child: [],
        icon: 'bumper_small.jpg',
        image: 'bumper_medium.jpg',
        seoTitle: 'Крепления бампера/деталей бампера',
        seoDescription: 'Крепления бампера/деталей бампера',
        seoKeywords: 'Крепления бампера/деталей бампера',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: '0b522c3f-6e38-4cc5-adf4-1280f90da7e2',
        id1C: '000000098',
        parentId1C: '000000011',
        title: 'Крепления обшивки, 1 шляпка',
        stringKey: 'krepleniya-obshivki-1-shlyapka000000098-69e6bae',
        showCategory: false,
        child: [],
        icon: 'obshivka_1s_small.jpg',
        image: 'obshivka_1s_medium.jpg',
        seoTitle: 'Крепления обшивки, одна шляпка',
        seoDescription: 'Крепления обшивки, одна шляпка',
        seoKeywords: 'Крепления обшивки, одна шляпка',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: '2811d843-6df4-4634-9b00-d155165027b1',
        id1C: '000000109',
        parentId1C: '000000011',
        title: 'Крепления обшивки/молдингов, ≥2 шляпок',
        stringKey: 'krepleniya-obshivkimoldingov-2-shlyapok000000109-85982c13',
        showCategory: false,
        child: [],
        icon: 'obshivka_2s_small.jpg',
        image: 'obshivka_2s_medium.jpg',
        seoTitle: 'Крепления обшивки, молдингов, две и более шляпок',
        seoDescription: 'Крепления обшивки, молдингов, две и более шляпок',
        seoKeywords: 'Крепления обшивки, молдингов, две и более шляпок',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: 'edc1dfa3-a10e-4c0f-8366-2cb67117f4ef',
        id1C: '000000110',
        parentId1C: '000000011',
        title: 'Крепления опоры капота, шлангов, проводов',
        stringKey:
          'krepleniya-opory-kapota-shlangov-provodov000000110-10dd2ba5',
        showCategory: false,
        child: [],
        icon: 'BonnetMountingsHoses_small.jpg',
        image: 'BonnetMountingsHoses_medium.jpg',
        seoTitle: 'Крепления опоры капота, шлангов, проводов',
        seoDescription: 'Крепления опоры капота, шлангов, проводов',
        seoKeywords: 'Крепления опоры капота, шлангов, проводов',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: 'c7997be6-b246-428c-8f6f-140c18883dd7',
        id1C: '000000111',
        parentId1C: '000000011',
        title: 'Крепления распорного действия',
        stringKey: 'krepleniya-raspornogo-dejstviya000000111-51934875',
        showCategory: false,
        child: [],
        icon: 'SpacerMounts_small.jpg',
        image: 'SpacerMounts_medium.jpg',
        seoTitle: 'Крепления распорного действия',
        seoDescription: 'Крепления распорного действия',
        seoKeywords: 'Крепления распорного действия',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: '01faa669-b274-4959-b55b-ff2add4840de',
        id1C: '000000112',
        parentId1C: '000000011',
        title: 'Отбойники, крепления полки',
        stringKey: 'otbojniki-krepleniya-polki000000112-10668411',
        showCategory: false,
        child: [],
        icon: 'ChippersShelfMounts_small.jpg',
        image: 'ChippersShelfMounts_medium.jpg',
        seoTitle: 'Отбойники, крепления полки',
        seoDescription: 'Отбойники, крепления полки',
        seoKeywords: 'Отбойники, крепления полки',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: '1a819d45-e1df-4951-80f9-3ac4c0163215',
        id1C: '000000113',
        parentId1C: '000000011',
        title: 'Ролики',
        stringKey: 'roliki000000113-917c745b',
        showCategory: false,
        child: [],
        icon: 'Rollers_small.jpg',
        image: 'Rollers_medium.jpg',
        seoTitle: 'Ролики',
        seoDescription: 'Ролики',
        seoKeywords: 'Ролики',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: 'a87280be-84b1-4e6d-bc6c-012e1c7609d6',
        id1C: '000000114',
        parentId1C: '000000011',
        title: 'Саморезы',
        stringKey: 'samorezy000000114-e3b0e942',
        showCategory: false,
        child: [],
        icon: 'Screws_small.jpg',
        image: 'Screws_medium.jpg',
        seoTitle: 'Саморезы',
        seoDescription: 'Саморезы',
        seoKeywords: 'Саморезы',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: '323a48f5-2ea2-411c-8a6d-46a3ea963743',
        id1C: '000000115',
        parentId1C: '000000011',
        title: 'Стеклоподъемники',
        stringKey: 'steklopodemniki000000115-2f03f01',
        showCategory: false,
        child: [],
        icon: 'Powerwindows_small.jpg',
        image: 'Powerwindows_medium.jpg',
        seoTitle: 'Стеклоподъемники',
        seoDescription: 'Стеклоподъемники',
        seoKeywords: 'Стеклоподъемники',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: '69ab0e64-45fa-4f2b-bc2d-2439ff13fdab',
        id1C: '000000126',
        parentId1C: '000000011',
        title: 'Стопорные кольца',
        stringKey: 'stopornye-kolca000000126-d6ace0a5',
        showCategory: false,
        child: [],
        icon: 'retaining_ring_small.jpg',
        image: 'retaining_ring_medium.jpg',
        seoTitle: 'Стопорные кольца',
        seoDescription: 'Стопорные кольца',
        seoKeywords: 'Стопорные кольца',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: '9ff58411-7d36-41d6-a889-17b1d67d13c1',
        id1C: '000000116',
        parentId1C: '000000011',
        title: 'Фигурные',
        stringKey: 'figurnye000000116-2dc181c5',
        showCategory: false,
        child: [],
        icon: 'Curly_small.jpg',
        image: 'Curly_medium.jpg',
        seoTitle: 'Фигурные',
        seoDescription: 'Фигурные',
        seoKeywords: 'Фигурные',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: '3518ecd3-01ba-461a-b143-8d567437ee62',
        id1C: '000000117',
        parentId1C: '000000011',
        title: 'Фиксаторы, закладные',
        stringKey: 'fiksatory-zakladnye000000117-d5f7e125',
        showCategory: false,
        child: [],
        icon: 'ClampsMortgages_small.jpg',
        image: 'ClampsMortgages_medium.jpg',
        seoTitle: 'Фиксаторы, закладные',
        seoDescription: 'Фиксаторы, закладные',
        seoKeywords: 'Фиксаторы, закладные',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: 'd552a295-9b35-480e-88d8-c02056271fb7',
        id1C: '000000118',
        parentId1C: '000000011',
        title: 'Фитинги, форсунки омывателя',
        stringKey: 'fitingi-forsunki-omyvatelya000000118-4e762fe1',
        showCategory: false,
        child: [],
        icon: 'Washerfittingnozzle_small.jpg',
        image: 'Washerfittingnozzle_medium.jpg',
        seoTitle: 'Фитинги, форсунки омывателя',
        seoDescription: 'Фитинги, форсунки омывателя',
        seoKeywords: 'Фитинги, форсунки омывателя',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: 'e148cddd-35bc-4d23-a950-81d3156854fe',
        id1C: '000000119',
        parentId1C: '000000011',
        title: 'Хомуты',
        stringKey: 'xomuty000000119-c660e328',
        showCategory: false,
        child: [],
        icon: 'Clamps_small.jpg',
        image: 'Clamps_medium.jpg',
        seoTitle: 'Хомуты',
        seoDescription: 'Хомуты',
        seoKeywords: 'Хомуты',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: '97037aa5-b669-494d-bf2d-f26c3fcb2201',
        id1C: '000000080',
        parentId1C: '000000011',
        title: 'Шплинты',
        stringKey: 'shplinty000000080-d6a0da97',
        showCategory: false,
        child: [],
        icon: 'splint_small.jpg',
        image: 'splint_medium.jpg',
        seoTitle: 'Шплинты',
        seoDescription: 'Шплинты',
        seoKeywords: 'Шплинты',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
      {
        id: '0099ce78-fcd5-4482-8f15-ffde6bb605a7',
        id1C: '000000085',
        parentId1C: '000000011',
        title: 'Универсальные',
        stringKey: 'universalnye000000085-bf752540',
        showCategory: false,
        child: [],
        seoTitle: 'Универсальные',
        seoDescription: 'Универсальные',
        seoKeywords: 'Универсальные',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Элементы крепления',
            url: 'elementy-krepleniya000000011-beeaef37',
          },
        ],
        isHasChild: false,
      },
    ],
    icon: 'klipsy_small.jpg',
    image: 'klipsy_medium.jpg',
    seoTitle: '',
    seoDescription: '',
    seoKeywords: '',
    isMain: true,
    isSale: false,
    isDropDownMenu: false,
    breadcrumbs: [{ title: 'Каталоги', url: '/catalog' }],
    isHasChild: true,
  },
  {
    id: 'a042eb61-a96a-4638-9eda-37bd9b42c55d',
    id1C: '000000024',
    title: 'Технические жидкости',
    stringKey: 'texnicheskie-zhidkosti000000024-912bf367',
    showCategory: false,
    child: [
      {
        id: '5308ba4d-8f7f-42d4-93a8-8a721075c295',
        id1C: '000000030',
        parentId1C: '000000024',
        title: 'AdBlue',
        stringKey: 'adblue000000030-57471b23',
        showCategory: false,
        child: [],
        icon: 'tech_liq_small.jpg',
        image: 'tech_liq_medium.jpg',
        seoTitle: '',
        seoDescription: '',
        seoKeywords: '',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Технические жидкости',
            url: 'texnicheskie-zhidkosti000000024-912bf367',
          },
        ],
        isHasChild: false,
      },
      {
        id: '8cdf3705-c070-4439-96fd-7af8224748f3',
        id1C: '000000070',
        parentId1C: '000000024',
        title: 'Охлаждающие жидкости',
        stringKey: 'oxlazhdayushhie-zhidkosti000000070-c8e136f6',
        showCategory: false,
        child: [],
        icon: 'antifreeze_small.jpg',
        image: 'antifreeze_medium.jpg',
        seoTitle: 'Охлаждающие жидкости',
        seoDescription: 'Охлаждающие жидкости',
        seoKeywords: 'Охлаждающие жидкости',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Технические жидкости',
            url: 'texnicheskie-zhidkosti000000024-912bf367',
          },
        ],
        isHasChild: false,
      },
      {
        id: '98b54d9e-c277-4750-afe0-99e70ba7531b',
        id1C: '000000071',
        parentId1C: '000000024',
        title: 'Тормозные жидкости',
        stringKey: 'tormoznye-zhidkosti000000071-af3f6ad2',
        showCategory: false,
        child: [],
        icon: 'brake_fluids_small.jpg',
        image: 'brake_fluids_medium.jpg',
        seoTitle: 'Тормозные жидкости',
        seoDescription: 'Тормозные жидкости',
        seoKeywords: 'Тормозные жидкости',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Технические жидкости',
            url: 'texnicheskie-zhidkosti000000024-912bf367',
          },
        ],
        isHasChild: false,
      },
    ],
    icon: 'tech_liq_small.jpg',
    image: 'tech_liq_medium.jpg',
    seoTitle: '',
    seoDescription: '',
    seoKeywords: '',
    isMain: true,
    isSale: false,
    isDropDownMenu: false,
    breadcrumbs: [{ title: 'Каталоги', url: '/catalog' }],
    isHasChild: true,
  },
  {
    id: '45db2f5c-327c-4371-8fc5-37dd4885c98c',
    id1C: '000000010',
    title: 'Щётки стеклоочистителя',
    stringKey: 'shhyotki-stekloochistitelya000000010-6ebf8866',
    showCategory: false,
    child: [],
    icon: 'wipers_small.jpg',
    image: 'wipers_medium.jpg',
    seoTitle: '',
    seoDescription: '',
    seoKeywords: '',
    isMain: true,
    isSale: false,
    isDropDownMenu: false,
    breadcrumbs: [{ title: 'Каталоги', url: '/catalog' }],
    isHasChild: false,
  },
  {
    id: 'e8a1ce6f-703c-4d31-af29-417398f07ce3',
    id1C: '000000128',
    title: 'Упоры газовые',
    stringKey: 'upory-gazovye000000128-79d1372c',
    showCategory: false,
    child: [],
    icon: 'gasspring_small.jpg',
    image: 'gasspring_medium.jpg',
    seoTitle: '',
    seoDescription: '',
    seoKeywords: '',
    isMain: true,
    isSale: false,
    isDropDownMenu: false,
    breadcrumbs: [{ title: 'Каталоги', url: '/catalog' }],
    isHasChild: false,
  },
  {
    id: 'fa2a9ee0-35a1-432c-a208-554ed78e64c5',
    id1C: '000000009',
    title: 'Выхлопная система',
    stringKey: 'vyxlopnaya-sistema000000009-e942c150',
    showCategory: false,
    child: [],
    icon: 'gofra_small.jpg',
    image: 'gofra_medium.jpg',
    seoTitle: '',
    seoDescription: '',
    seoKeywords: '',
    isMain: true,
    isSale: false,
    isDropDownMenu: false,
    breadcrumbs: [{ title: 'Каталоги', url: '/catalog' }],
    isHasChild: false,
  },
  {
    id: 'c7e89b9c-7885-4e19-9ad3-57897068435d',
    id1C: '000000121',
    title: 'Рессоры',
    stringKey: 'ressory000000121-1e32465a',
    showCategory: false,
    child: [],
    icon: 'ressory_small.jpg',
    image: 'ressory_medium.jpg',
    seoTitle: 'Рессоры',
    seoDescription: 'Рессоры',
    seoKeywords: 'Рессоры',
    isMain: true,
    isSale: false,
    isDropDownMenu: false,
    breadcrumbs: [{ title: 'Каталоги', url: '/catalog' }],
    isHasChild: false,
  },
  {
    id: '41332853-67a6-4c59-b669-61c03954b4f4',
    id1C: '000000005',
    title: 'Шины',
    stringKey: 'shiny000000005-7b5ba913',
    showCategory: false,
    child: [
      {
        id: '87b8778e-f9b9-4d43-9aa1-7fe157631ad2',
        id1C: '000000016',
        parentId1C: '000000005',
        title: 'Легковые',
        stringKey: 'legkovye000000016-334a464b',
        showCategory: false,
        child: [],
        icon: 'Passenger_car_small.jpg',
        image: 'Passenger_car_medium.jpg',
        seoTitle: '',
        seoDescription: '',
        seoKeywords: '',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          { title: 'Шины', url: 'shiny000000005-7b5ba913' },
        ],
        isHasChild: false,
      },
      {
        id: '6811cca7-cca6-4685-a216-b491d8787944',
        id1C: '000000017',
        parentId1C: '000000005',
        title: 'Легкогрузовые',
        stringKey: 'legkogruzovye000000017-d343a109',
        showCategory: false,
        child: [],
        icon: 'mini_bus_tyre_small.jpg',
        image: 'mini_bus_tyre_medium.jpg',
        seoTitle: '',
        seoDescription: '',
        seoKeywords: '',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          { title: 'Шины', url: 'shiny000000005-7b5ba913' },
        ],
        isHasChild: false,
      },
      {
        id: '29010dc6-b043-4bf4-b1f9-060baef2beee',
        id1C: '000000013',
        parentId1C: '000000005',
        title: 'Грузовые',
        stringKey: 'gruzovye000000013-f0acdbc8',
        showCategory: false,
        child: [],
        icon: 'truck_tyre_small.jpg',
        image: 'truck_tyre_medium.jpg',
        seoTitle: 'Купить грузовые шины | Тирасполь | ТирАвто',
        seoDescription: 'Купить грузовые шины в Тирасполе | ТирАвто',
        seoKeywords: 'Купить грузовые шины | Тирасполь | ТирАвто',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          { title: 'Шины', url: 'shiny000000005-7b5ba913' },
        ],
        isHasChild: false,
      },
      {
        id: '8069db5c-db2b-4a16-a777-f38468748287',
        id1C: '000000019',
        parentId1C: '000000005',
        title: 'Сельскохозяйственные',
        stringKey: 'selskoxozyajstvennye000000019-9c8c6964',
        showCategory: false,
        child: [],
        icon: 'agro_tyre_small.jpg',
        image: 'agro_tyre_medium.jpg',
        seoTitle: '',
        seoDescription: '',
        seoKeywords: '',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          { title: 'Шины', url: 'shiny000000005-7b5ba913' },
        ],
        isHasChild: false,
      },
      {
        id: '021a549a-32de-4de6-96f4-7f104f987f28',
        id1C: '000000018',
        parentId1C: '000000005',
        title: 'Внедорожники и кроссоверы',
        stringKey: 'vnedorozhniki-i-krossovery000000018-96c1635',
        showCategory: false,
        child: [],
        icon: 'allroad_tyre_small.jpg',
        image: 'allroad_tyre_medium.jpg',
        seoTitle: '',
        seoDescription: '',
        seoKeywords: '',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          { title: 'Шины', url: 'shiny000000005-7b5ba913' },
        ],
        isHasChild: false,
      },
      {
        id: 'afdd6f1a-9eac-441a-b7ae-edf0a4012505',
        id1C: '000000123',
        parentId1C: '000000005',
        title: 'Индустриальные',
        stringKey: 'industrialnye000000123-862dfd1a',
        showCategory: false,
        child: [],
        icon: 'ind_small.jpg',
        image: 'ind_medium.jpg',
        seoTitle: 'Шины индустриальные',
        seoDescription: 'Шины индустриальные',
        seoKeywords: 'купить шины индустриальные тирасполь ',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          { title: 'Шины', url: 'shiny000000005-7b5ba913' },
        ],
        isHasChild: false,
      },
    ],
    icon: 'shina_small.jpg',
    image: 'shina_medium.jpg',
    seoTitle: '',
    seoDescription: '',
    seoKeywords: '',
    isMain: true,
    isSale: false,
    isDropDownMenu: false,
    breadcrumbs: [{ title: 'Каталоги', url: '/catalog' }],
    isHasChild: true,
  },
  {
    id: '106493eb-ec4b-4341-98ee-6ce1e6927f95',
    id1C: '000000035',
    title: 'Спецодежда и средства защиты',
    stringKey: 'specodezhda-i-sredstva-zashhity000000035-ce4353d',
    showCategory: false,
    child: [],
    icon: 'overalls_small.jpg',
    image: 'overalls_medium.jpg',
    seoTitle: '',
    seoDescription: '',
    seoKeywords: '',
    isMain: true,
    isSale: false,
    isDropDownMenu: false,
    breadcrumbs: [{ title: 'Каталоги', url: '/catalog' }],
    isHasChild: false,
  },
  {
    id: '08b18e0b-d879-4d03-b5d4-7460e5b65fb6',
    id1C: '000000006',
    title: 'Аксессуары',
    stringKey: 'aksessuary000000006-8c94abeb',
    showCategory: false,
    child: [
      {
        id: '333cd884-9f05-42e6-bf9e-bd1a9d6800ca',
        id1C: '000000047',
        parentId1C: '000000006',
        title: 'Автогаджеты и девайсы',
        stringKey: 'avtogadzhety-i-devajsy000000047-f152d56e',
        showCategory: false,
        child: [],
        icon: 'devices_small.jpg',
        image: 'devices_medium.jpg',
        seoTitle: 'Автогаджеты и девайсы',
        seoDescription: 'Автогаджеты и девайсы',
        seoKeywords: 'Автогаджеты и девайсы',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          { title: 'Аксессуары', url: 'aksessuary000000006-8c94abeb' },
        ],
        isHasChild: false,
      },
      {
        id: '15a6ee48-13f3-4469-b4bc-6586c81edc05',
        id1C: '000000048',
        parentId1C: '000000006',
        title: 'Аксессуары первой необходимости',
        stringKey: 'aksessuary-pervoj-neobxodimosti000000048-18f4af53',
        showCategory: false,
        child: [],
        icon: 'first_aid_products_small.jpg',
        image: 'first_aid_products_medium.jpg',
        seoTitle: 'Аксессуары ПЕРВОЙ необходимости',
        seoDescription: 'Аксессуары ПЕРВОЙ необходимости',
        seoKeywords: 'Аксессуары ПЕРВОЙ необходимости',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          { title: 'Аксессуары', url: 'aksessuary000000006-8c94abeb' },
        ],
        isHasChild: false,
      },
      {
        id: 'cb94122d-fce1-4b76-a3da-048f5186cc4c',
        id1C: '000000036',
        parentId1C: '000000006',
        title: 'Ароматизаторы',
        stringKey: 'aromatizatory000000036-68c06449',
        showCategory: false,
        child: [],
        icon: 'airfreshener_small.jpg',
        image: 'airfreshener_medium.jpg',
        seoTitle: '',
        seoDescription: '',
        seoKeywords: '',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          { title: 'Аксессуары', url: 'aksessuary000000006-8c94abeb' },
        ],
        isHasChild: false,
      },
      {
        id: '1fa67dbb-023e-4d59-9515-7f22fc9bcb78',
        id1C: '000000051',
        parentId1C: '000000006',
        title: 'Детские автокресла',
        stringKey: 'detskie-avtokresla000000051-e322d4e0',
        showCategory: false,
        child: [],
        icon: 'car_seats2_small.jpg',
        image: 'car_seats2_medium.jpg',
        seoTitle: 'Детские автокресла',
        seoDescription: 'Детские автокресла',
        seoKeywords: 'Детские автокресла',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          { title: 'Аксессуары', url: 'aksessuary000000006-8c94abeb' },
        ],
        isHasChild: false,
      },
      {
        id: '645270a1-6e72-4029-a202-3c10d0550c65',
        id1C: '000000049',
        parentId1C: '000000006',
        title: 'Зеркала и линзы',
        stringKey: 'zerkala-i-linzy000000049-b1b45673',
        showCategory: false,
        child: [],
        icon: 'car_mirrors_small.jpg',
        image: 'car_mirrors_medium.jpg',
        seoTitle: 'Зеркала и линзы',
        seoDescription: 'Зеркала и линзы',
        seoKeywords: 'Зеркала и линзы',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          { title: 'Аксессуары', url: 'aksessuary000000006-8c94abeb' },
        ],
        isHasChild: false,
      },
      {
        id: 'c3b2e78b-c1bb-4c71-8762-3a11f57b521d',
        id1C: '000000065',
        parentId1C: '000000006',
        title: 'Интерьер',
        stringKey: 'interer000000065-1de0ee65',
        showCategory: false,
        child: [],
        icon: 'interior_small.jpg',
        image: 'interior_medium.jpg',
        seoTitle: 'Интерьер',
        seoDescription: 'Интерьер',
        seoKeywords: 'Интерьер',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          { title: 'Аксессуары', url: 'aksessuary000000006-8c94abeb' },
        ],
        isHasChild: false,
      },
      {
        id: '6e57a249-89a0-4817-b4e4-86f06cdc3458',
        id1C: '000000054',
        parentId1C: '000000006',
        title: 'Колпаки колесные',
        stringKey: 'kolpaki-kolesnye000000054-216f1f00',
        showCategory: false,
        child: [],
        icon: 'kolpaki_small.jpg',
        image: 'kolpaki_medium.jpg',
        seoTitle: 'Колпаки',
        seoDescription: 'Колпаки',
        seoKeywords: 'Колпаки',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          { title: 'Аксессуары', url: 'aksessuary000000006-8c94abeb' },
        ],
        isHasChild: false,
      },
      {
        id: 'a9ffa650-1c70-4560-8ce4-c4abc6c5797f',
        id1C: '000000052',
        parentId1C: '000000006',
        title: 'Охранные системы',
        stringKey: 'oxrannye-sistemy000000052-d768b181',
        showCategory: false,
        child: [],
        icon: 'security_system_small.jpg',
        image: 'security_system_medium.jpg',
        seoTitle: 'Охранные системы',
        seoDescription: 'Охранные системы',
        seoKeywords: 'Охранные системы',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          { title: 'Аксессуары', url: 'aksessuary000000006-8c94abeb' },
        ],
        isHasChild: false,
      },
      {
        id: '9eea99fd-e737-4814-a2f5-77c7fd4d720c',
        id1C: '000000041',
        parentId1C: '000000006',
        title: 'Ленты на клейкой основе',
        stringKey: 'lenty-na-klejkoj-osnove000000041-77753d4c',
        showCategory: false,
        child: [],
        seoTitle: 'Элементы крепления',
        seoDescription: 'Элементы крепления',
        seoKeywords: 'Элементы крепления',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          { title: 'Аксессуары', url: 'aksessuary000000006-8c94abeb' },
        ],
        isHasChild: false,
      },
      {
        id: '4a013a0b-2793-4d63-ad51-f4fc338bc349',
        id1C: '000000037',
        parentId1C: '000000006',
        title: 'Протирочные материалы',
        stringKey: 'protirochnye-materialy000000037-a1a2284c',
        showCategory: false,
        child: [],
        icon: 'wiping_cloth_small.jpg',
        image: 'wiping_cloth_medium.jpg',
        seoTitle: '',
        seoDescription: '',
        seoKeywords: '',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          { title: 'Аксессуары', url: 'aksessuary000000006-8c94abeb' },
        ],
        isHasChild: false,
      },
      {
        id: 'db8494c3-64a1-4c23-aba1-698e036b0767',
        id1C: '000000042',
        parentId1C: '000000006',
        title: 'Ремонт и обслуживание колес',
        stringKey: 'remont-i-obsluzhivanie-koles000000042-3b1d2fca',
        showCategory: false,
        child: [],
        icon: 'domkrat_small.jpg',
        image: 'domkrat_medium.jpg',
        seoTitle: 'Ремонт и обслуживание колес',
        seoDescription: 'Ремонт и обслуживание колес',
        seoKeywords: 'Ремонт и обслуживание колес',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          { title: 'Аксессуары', url: 'aksessuary000000006-8c94abeb' },
        ],
        isHasChild: false,
      },
      {
        id: '92f9f243-e06e-4b2d-ad95-b57fc219101c',
        id1C: '000000044',
        parentId1C: '000000006',
        title: 'Скребки, Щетки, Лопаты',
        stringKey: 'skrebki-shhetki-lopaty000000044-b8242f42',
        showCategory: false,
        child: [],
        icon: 'skrebok_small.jpg',
        image: 'skrebok_medium.jpg',
        seoTitle: 'Скребки, Щетки, Лопаты',
        seoDescription: 'Скребки, Щетки, Лопаты',
        seoKeywords: 'Скребки, Щетки, Лопаты',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          { title: 'Аксессуары', url: 'aksessuary000000006-8c94abeb' },
        ],
        isHasChild: false,
      },
      {
        id: 'd1b75251-51a9-435e-9fb0-e15ff33c3af5',
        id1C: '000000066',
        parentId1C: '000000006',
        title: 'Сувенирная продукция',
        stringKey: 'suvenirnaya-produkciya000000066-a175231a',
        showCategory: false,
        child: [],
        icon: 'souvenir_small.jpg',
        image: 'souvenir_medium.jpg',
        seoTitle: 'Сувенирная продукция',
        seoDescription: 'Сувенирная продукция',
        seoKeywords: 'Сувенирная продукция',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          { title: 'Аксессуары', url: 'aksessuary000000006-8c94abeb' },
        ],
        isHasChild: false,
      },
      {
        id: '0af0a7b3-d497-4224-b942-553b485ee4f7',
        id1C: '000000046',
        parentId1C: '000000006',
        title: 'Тенты и шторки',
        stringKey: 'tenty-i-shtorki000000046-1f20fdad',
        showCategory: false,
        child: [],
        icon: 'tents_small.jpg',
        image: 'tents_medium.jpg',
        seoTitle: 'Тенты, Чехлы, Шторки',
        seoDescription: 'Тенты, Чехлы, Шторки',
        seoKeywords: 'Тенты, Чехлы, Шторки',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          { title: 'Аксессуары', url: 'aksessuary000000006-8c94abeb' },
        ],
        isHasChild: false,
      },
      {
        id: 'd81d1723-edad-479e-9611-e6709180da3a',
        id1C: '000000045',
        parentId1C: '000000006',
        title: 'Хранение и порядок в авто',
        stringKey: 'xranenie-i-poryadok-v-avto000000045-9a18e5e6',
        showCategory: false,
        child: [],
        icon: 'storage_small.jpg',
        image: 'storage_medium.jpg',
        seoTitle: 'Хранение и порядок в авто',
        seoDescription: 'Хранение и порядок в авто',
        seoKeywords: 'Хранение и порядок в авто',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          { title: 'Аксессуары', url: 'aksessuary000000006-8c94abeb' },
        ],
        isHasChild: false,
      },
      {
        id: '1aa5ea01-eba4-47fd-80aa-8c94186e4316',
        id1C: '000000050',
        parentId1C: '000000006',
        title: 'Экстерьер',
        stringKey: 'eksterer000000050-c63d3724',
        showCategory: false,
        child: [],
        icon: 'exterior_small.jpg',
        image: 'exterior_medium.jpg',
        seoTitle: 'Экстерьер',
        seoDescription: 'Экстерьер',
        seoKeywords: 'Экстерьер',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          { title: 'Аксессуары', url: 'aksessuary000000006-8c94abeb' },
        ],
        isHasChild: false,
      },
      {
        id: '3660a5d6-9574-44df-8882-adb7510ba305',
        id1C: '000000053',
        parentId1C: '000000006',
        title: 'Уход за авто',
        stringKey: 'uxod-za-avto000000053-edc14b90',
        showCategory: false,
        child: [],
        icon: 'vacuum_cleaner_small.jpg',
        image: 'vacuum_cleaner_medium.jpg',
        seoTitle: 'Уход за авто',
        seoDescription: 'Уход за авто',
        seoKeywords: 'Уход за авто',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          { title: 'Аксессуары', url: 'aksessuary000000006-8c94abeb' },
        ],
        isHasChild: false,
      },
      {
        id: 'c3775d57-d46b-41ef-87e0-9c2d6278be50',
        id1C: '000000122',
        parentId1C: '000000006',
        title: 'Шумоизоляция',
        stringKey: 'shumoizolyaciya000000122-bba069ed',
        showCategory: false,
        child: [],
        icon: 'noiseproof_small.jpg',
        image: 'noiseproof_medium.jpg',
        seoTitle: 'Шумоизоляция',
        seoDescription: 'Шумоизоляция',
        seoKeywords: 'Шумоизоляция',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          { title: 'Аксессуары', url: 'aksessuary000000006-8c94abeb' },
        ],
        isHasChild: false,
      },
    ],
    icon: 'F176A58BC29AB5E302B294255747D119',
    image: 'F176A58BC29AB5E302B294255747D119',
    seoTitle: '',
    seoDescription: '',
    seoKeywords: '',
    isMain: true,
    isSale: false,
    isDropDownMenu: false,
    breadcrumbs: [{ title: 'Каталоги', url: '/catalog' }],
    isHasChild: true,
  },
  {
    id: '31589e47-d0d2-452b-9f58-80436abf825a',
    id1C: '000000075',
    title: 'Система кондиционирования',
    stringKey: 'sistema-kondicionirovaniya000000075-98dc7ce1',
    showCategory: false,
    child: [],
    icon: 'air_conditioning_small.jpg',
    image: 'air_conditioning_medium.jpg',
    seoTitle: 'Система кондиционирования',
    seoDescription: 'Система кондиционирования',
    seoKeywords: 'Система кондиционирования',
    isMain: true,
    isSale: false,
    isDropDownMenu: false,
    breadcrumbs: [{ title: 'Каталоги', url: '/catalog' }],
    isHasChild: false,
  },
  {
    id: '459eb92a-be6f-4533-861a-96c8b108b5b8',
    id1C: '000000007',
    title: 'Коврики салона и багажника',
    stringKey: 'kovriki-salona-i-bagazhnika000000007-81d64d9c',
    showCategory: false,
    child: [
      {
        id: '64c84994-fe90-4428-bc1a-92e8be001ee1',
        id1C: '000000014',
        parentId1C: '000000007',
        title: 'Модельные',
        stringKey: 'modelnye000000014-37ee0797',
        showCategory: false,
        child: [],
        icon: 'model_mats_small.jpg',
        image: 'model_mats_medium.jpg',
        seoTitle: '',
        seoDescription: '',
        seoKeywords: '',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Коврики салона и багажника',
            url: 'kovriki-salona-i-bagazhnika000000007-81d64d9c',
          },
        ],
        isHasChild: false,
      },
      {
        id: 'aa105b9e-5fcb-4241-8e83-0bde095a9425',
        id1C: '000000015',
        parentId1C: '000000007',
        title: 'Универсальные',
        stringKey: 'universalnye000000015-911a3622',
        showCategory: false,
        child: [],
        icon: 'universal_mats_small.jpg',
        image: 'universal_mats_medium.jpg',
        seoTitle: '',
        seoDescription: '',
        seoKeywords: '',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Коврики салона и багажника',
            url: 'kovriki-salona-i-bagazhnika000000007-81d64d9c',
          },
        ],
        isHasChild: false,
      },
    ],
    icon: 'carpets_small.jpg',
    image: 'carpets_medium.jpg',
    seoTitle: '',
    seoDescription: '',
    seoKeywords: '',
    isMain: true,
    isSale: false,
    isDropDownMenu: false,
    breadcrumbs: [{ title: 'Каталоги', url: '/catalog' }],
    isHasChild: true,
  },
  {
    id: '5068910f-3d6e-40e9-8128-9a56fa15c0d0',
    id1C: '000000125',
    title: 'Подшипники',
    stringKey: 'podshipniki000000125-25de055b',
    showCategory: false,
    child: [],
    icon: 'bearing_small.jpg',
    image: 'bearing_medium.jpg',
    seoTitle: 'Каталог подшипников',
    seoDescription: 'Каталог подшипников',
    seoKeywords: 'Каталог подшипников',
    isMain: true,
    isSale: false,
    isDropDownMenu: false,
    breadcrumbs: [{ title: 'Каталоги', url: '/catalog' }],
    isHasChild: false,
  },
  {
    id: '3a3cf34d-8013-43e3-8d27-9ca5539f7f74',
    id1C: '000000008',
    title: 'Лампы',
    stringKey: 'lampy000000008-ee6817a1',
    showCategory: false,
    child: [],
    icon: 'lamps_small.jpg',
    image: 'lamps_medium.jpg',
    seoTitle: 'Лампы',
    seoDescription: 'Лампы',
    seoKeywords: 'Лампы',
    isMain: true,
    isSale: false,
    isDropDownMenu: false,
    breadcrumbs: [{ title: 'Каталоги', url: '/catalog' }],
    isHasChild: false,
  },
  {
    id: '9a3c9ad4-e663-4928-8e63-db9d03e106f0',
    id1C: '000000001',
    title: 'Смазочные материалы',
    stringKey: 'smazochnye-materialy000000001-c347037',
    showCategory: false,
    child: [
      {
        id: '2773dcdd-0a7a-47ea-bfff-90c732ccc457',
        id1C: '000000020',
        parentId1C: '000000001',
        title: 'Масла моторные',
        stringKey: 'masla-motornye000000020-575e06a8',
        showCategory: false,
        child: [],
        icon: 'motor_oil_small.jpg',
        image: 'motor_oil_medium.jpg',
        seoTitle: '',
        seoDescription: '',
        seoKeywords: '',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Смазочные материалы',
            url: 'smazochnye-materialy000000001-c347037',
          },
        ],
        isHasChild: false,
      },
      {
        id: '056c0945-f676-4ebe-a8c2-7e07bb1a1c17',
        id1C: '000000021',
        parentId1C: '000000001',
        title: 'Масла трансмиссионные',
        stringKey: 'masla-transmissionnye000000021-8ed2e3af',
        showCategory: false,
        child: [],
        icon: 'transmission_oil_small.jpg',
        image: 'transmission_oil_medium.jpg',
        seoTitle: '',
        seoDescription: '',
        seoKeywords: '',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Смазочные материалы',
            url: 'smazochnye-materialy000000001-c347037',
          },
        ],
        isHasChild: false,
      },
      {
        id: 'ca0c5d09-1ae8-4cf9-94e0-922a19c3b960',
        id1C: '000000022',
        parentId1C: '000000001',
        title: 'Масла гидравлические',
        stringKey: 'masla-gidravlicheskie000000022-36145c75',
        showCategory: false,
        child: [],
        icon: 'hidraulic_oils_small.jpg',
        image: 'hidraulic_oils_medium.jpg',
        seoTitle: '',
        seoDescription: '',
        seoKeywords: '',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Смазочные материалы',
            url: 'smazochnye-materialy000000001-c347037',
          },
        ],
        isHasChild: false,
      },
      {
        id: 'ab75d533-289a-47bd-b6a6-30a5f6077f13',
        id1C: '000000038',
        parentId1C: '000000001',
        title: 'Масла компрессорные',
        stringKey: 'masla-kompressornye000000038-a1cb5d36',
        showCategory: false,
        child: [],
        icon: 'Kompressor_oil_small.jpg',
        image: 'Kompressor_oil_medium.jpg',
        seoTitle: '',
        seoDescription: '',
        seoKeywords: '',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Смазочные материалы',
            url: 'smazochnye-materialy000000001-c347037',
          },
        ],
        isHasChild: false,
      },
      {
        id: '99c542a8-9061-4328-b6a1-a9bdcd963449',
        id1C: '000000027',
        parentId1C: '000000001',
        title: 'Масла индустриальные',
        stringKey: 'masla-industrialnye000000027-b45dbaf4',
        showCategory: false,
        child: [],
        icon: 'industrial_oils_2_small.jpg',
        image: 'industrial_oils_2_medium.jpg',
        seoTitle: '',
        seoDescription: '',
        seoKeywords: '',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Смазочные материалы',
            url: 'smazochnye-materialy000000001-c347037',
          },
        ],
        isHasChild: false,
      },
      {
        id: '4fef94aa-08cb-4a36-af9c-6e889bf37a37',
        id1C: '000000023',
        parentId1C: '000000001',
        title: 'Масла для мототехники',
        stringKey: 'masla-dlya-mototexniki000000023-f11a2caa',
        showCategory: false,
        child: [],
        icon: 'moto_oils_2_small.jpg',
        image: 'moto_oils_2_medium.jpg',
        seoTitle: '',
        seoDescription: '',
        seoKeywords: '',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Смазочные материалы',
            url: 'smazochnye-materialy000000001-c347037',
          },
        ],
        isHasChild: false,
      },
      {
        id: '8d0e3062-6308-46b4-a801-433b925b7d89',
        id1C: '000000025',
        parentId1C: '000000001',
        title: 'Масла AGRO',
        stringKey: 'masla-agro000000025-f82e6fab',
        showCategory: false,
        child: [],
        icon: 'agro_oils_2_small.jpg',
        image: 'agro_oils_2_medium.jpg',
        seoTitle: '',
        seoDescription: '',
        seoKeywords: '',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Смазочные материалы',
            url: 'smazochnye-materialy000000001-c347037',
          },
        ],
        isHasChild: false,
      },
      {
        id: 'b70a9b89-267d-45ec-bf28-ff7b843ce24b',
        id1C: '000000026',
        parentId1C: '000000001',
        title: 'Смазки',
        stringKey: 'smazki000000026-3618908e',
        showCategory: false,
        child: [],
        icon: 'smazki_small.jpg',
        image: 'smazki_medium.jpg',
        seoTitle: '',
        seoDescription: '',
        seoKeywords: '',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Смазочные материалы',
            url: 'smazochnye-materialy000000001-c347037',
          },
        ],
        isHasChild: false,
      },
    ],
    icon: 'smaz_materialy_small.jpg',
    image: 'smaz_materialy_medium.jpg',
    seoTitle: '',
    seoDescription: '',
    seoKeywords: '',
    isMain: true,
    isSale: false,
    isDropDownMenu: false,
    breadcrumbs: [{ title: 'Каталоги', url: '/catalog' }],
    isHasChild: true,
  },
  {
    id: 'f4b8080b-d4ab-45bd-91f3-ee460dff370e',
    id1C: '000000127',
    title: 'Туризм и садоводство',
    stringKey: 'turizm-i-sadovodstvo000000127-238ba724',
    showCategory: false,
    child: [],
    icon: 'tourism_small.jpg',
    image: 'tourism_medium.jpg',
    seoTitle: 'Туризм и садоводство',
    seoDescription: 'Туризм и садоводство',
    seoKeywords: 'Туризм и садоводство',
    isMain: true,
    isSale: false,
    isDropDownMenu: false,
    breadcrumbs: [{ title: 'Каталоги', url: '/catalog' }],
    isHasChild: false,
  },
  {
    id: '555b4165-e3cb-47f9-acff-f2ff2a5676c8',
    id1C: '000000002',
    title: 'Аккумуляторы',
    stringKey: 'akkumulyatory000000002-bc2f9a84',
    showCategory: false,
    child: [],
    icon: 'battery_small.jpg',
    image: 'battery_medium.jpg',
    seoTitle: '',
    seoDescription: '',
    seoKeywords: '',
    isMain: true,
    isSale: false,
    isDropDownMenu: false,
    breadcrumbs: [{ title: 'Каталоги', url: '/catalog' }],
    isHasChild: false,
  },
  {
    id: '5a7d3234-cc2c-4be8-9913-f98ec137b4ad',
    id1C: '000000004',
    title: 'Инструмент и оборудование',
    stringKey: 'instrument-i-oborudovanie000000004-aa20ddbf',
    showCategory: false,
    child: [
      {
        id: '8cc86861-5689-4470-b971-880c5f9b4178',
        id1C: '000000055',
        parentId1C: '000000004',
        title: 'Диагностическое оборудование',
        stringKey: 'diagnosticheskoe-oborudovanie000000055-f90769a7',
        showCategory: false,
        child: [],
        icon: 'diagnostic_small.jpg',
        image: 'diagnostic_medium.jpg',
        seoTitle: 'Диагностическое оборудованиеДиагностическое оборудование',
        seoDescription: 'Диагностическое оборудование',
        seoKeywords: 'Диагностическое оборудование',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Инструмент и оборудование',
            url: 'instrument-i-oborudovanie000000004-aa20ddbf',
          },
        ],
        isHasChild: false,
      },
      {
        id: '22d47cf9-4440-427e-85bf-54f1ccfa72f0',
        id1C: '000000074',
        parentId1C: '000000004',
        title: 'Измерительный инструмент',
        stringKey: 'izmeritelnyj-instrument000000074-922e52aa',
        showCategory: false,
        child: [],
        icon: 'measuring_tool_small.jpg',
        image: 'measuring_tool_medium.jpg',
        seoTitle: 'Измерительный инструмент',
        seoDescription: 'Измерительный инструмент',
        seoKeywords: 'Измерительный инструмент',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Инструмент и оборудование',
            url: 'instrument-i-oborudovanie000000004-aa20ddbf',
          },
        ],
        isHasChild: false,
      },
      {
        id: 'd4f0339c-c217-49d8-a791-479bb0091212',
        id1C: '000000040',
        parentId1C: '000000004',
        title: 'Обслуживание АКБ',
        stringKey: 'obsluzhivanie-akb000000040-c9757e88',
        showCategory: false,
        child: [],
        icon: 'battery_service_small.jpg',
        image: 'battery_service_medium.jpg',
        seoTitle: 'Обслуживание АКБ',
        seoDescription: 'Обслуживание АКБ',
        seoKeywords: 'Обслуживание АКБ',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Инструмент и оборудование',
            url: 'instrument-i-oborudovanie000000004-aa20ddbf',
          },
        ],
        isHasChild: false,
      },
      {
        id: '5962586b-0f70-4ddb-ae26-8225b1c0ebce',
        id1C: '000000072',
        parentId1C: '000000004',
        title: 'Оборудование для автомойки',
        stringKey: 'oborudovanie-dlya-avtomojki000000072-db786379',
        showCategory: false,
        child: [],
        icon: 'car_wash_tools_small.jpg',
        image: 'car_wash_tools_medium.jpg',
        seoTitle: 'Оборудование для автомойки',
        seoDescription: 'Оборудование для автомойки',
        seoKeywords: 'Оборудование для автомойки',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Инструмент и оборудование',
            url: 'instrument-i-oborudovanie000000004-aa20ddbf',
          },
        ],
        isHasChild: false,
      },
      {
        id: 'b201d57a-855a-4115-aa95-d753e395ba19',
        id1C: '000000073',
        parentId1C: '000000004',
        title: 'Оборудование для СТО и специнструмент',
        stringKey: 'oborudovanie-dlya-sto-i-specinstrument000000073-5e34b980',
        showCategory: false,
        child: [],
        icon: 'car_service_eq_small.jpg',
        image: 'car_service_eq_medium.jpg',
        seoTitle: 'Оборудование для СТО и специальный инструмент',
        seoDescription: 'Оборудование для СТО и специальный инструмент',
        seoKeywords: 'Оборудование для СТО и специальный инструмент',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Инструмент и оборудование',
            url: 'instrument-i-oborudovanie000000004-aa20ddbf',
          },
        ],
        isHasChild: false,
      },
      {
        id: '51391b51-7f67-48b5-b4a0-fed3f1e81ece',
        id1C: '000000124',
        parentId1C: '000000004',
        title: 'Пневмоинструмент',
        stringKey: 'pnevmoinstrument000000124-dbb3139',
        showCategory: false,
        child: [],
        icon: 'pneu_tools_small_small.jpg',
        image: 'pneu_tools_small_medium.jpg',
        seoTitle: 'Пневмоинструмент',
        seoDescription: 'Пневмоинструмент',
        seoKeywords: 'Пневмоинструмент',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Инструмент и оборудование',
            url: 'instrument-i-oborudovanie000000004-aa20ddbf',
          },
        ],
        isHasChild: false,
      },
      {
        id: 'cd4929d5-a385-4a15-b4d2-1b9f64cf27b8',
        id1C: '000000039',
        parentId1C: '000000004',
        title: 'Расходные материалы',
        stringKey: 'rasxodnye-materialy000000039-9eb86835',
        showCategory: false,
        child: [],
        icon: 'consumables_small.jpg',
        image: 'consumables_medium.jpg',
        seoTitle: '',
        seoDescription: '',
        seoKeywords: '',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Инструмент и оборудование',
            url: 'instrument-i-oborudovanie000000004-aa20ddbf',
          },
        ],
        isHasChild: false,
      },
      {
        id: 'ce59c7ca-db89-4fe7-b75a-9feb52738bb1',
        id1C: '000000043',
        parentId1C: '000000004',
        title: 'Ручной инструмент',
        stringKey: 'ruchnoj-instrument000000043-705964b9',
        showCategory: false,
        child: [],
        icon: 'tools_small.jpg',
        image: 'tools_medium.jpg',
        seoTitle: 'Ручной инструмент',
        seoDescription: 'Ручной инструмент',
        seoKeywords: 'Ручной инструмент',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Инструмент и оборудование',
            url: 'instrument-i-oborudovanie000000004-aa20ddbf',
          },
        ],
        isHasChild: false,
      },
      {
        id: '3a8503f5-056f-4ba8-8e37-aa84a304b93e',
        id1C: '000000076',
        parentId1C: '000000004',
        title: 'Станки и силовое оборудование',
        stringKey: 'stanki-i-silovoe-oborudovanie000000076-9c2f9294',
        showCategory: false,
        child: [],
        icon: 'TC_BD_350_small.jpg',
        image: 'TC_BD_350_medium.jpg',
        seoTitle: 'Станки и силовое оборудование',
        seoDescription: 'Станки и силовое оборудование',
        seoKeywords: 'Станки и силовое оборудование',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Инструмент и оборудование',
            url: 'instrument-i-oborudovanie000000004-aa20ddbf',
          },
        ],
        isHasChild: false,
      },
      {
        id: '66d940c1-7684-4374-b091-6f246b3c3da5',
        id1C: '000000120',
        parentId1C: '000000004',
        title: 'Электроинструмент',
        stringKey: 'elektroinstrument000000120-52bf3d55',
        showCategory: false,
        child: [],
        icon: 'electrotools_small.jpg',
        image: 'electrotools_medium.jpg',
        seoTitle: 'Электроинструмент',
        seoDescription: 'Электроинструмент',
        seoKeywords: 'Электроинструмент',
        isMain: false,
        isSale: false,
        isDropDownMenu: true,
        breadcrumbs: [
          { title: 'Каталоги', url: '/catalog' },
          {
            title: 'Инструмент и оборудование',
            url: 'instrument-i-oborudovanie000000004-aa20ddbf',
          },
        ],
        isHasChild: false,
      },
    ],
    icon: 'A7199585779907A55992FA5C337D3427',
    image: 'A7199585779907A55992FA5C337D3427',
    seoTitle: 'Инструмент и оборудование',
    seoDescription: 'Инструмент и оборудование',
    seoKeywords: 'Инструмент и оборудование',
    isMain: true,
    isSale: false,
    isDropDownMenu: false,
    breadcrumbs: [{ title: 'Каталоги', url: '/catalog' }],
    isHasChild: true,
  },
];

